119 searchbar enhance the styling and fetch from supabase
202306-NEA-DZ-FEW/student-store-team-2 pull request #133
Opened 2023-11-18 23:37 UTC by Bolphunga

**Changes made:**
Migrated the search fetching from Firebase to Supabase.
Fixed the search bar positioning.

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/student-store-team-2/assets/138311944/9b5fa1cc-eecc-4f9e-9c1b-06c5cbc99910)
![image](https://github.com/202306-NEA-DZ-FEW/student-store-team-2/assets/138311944/def3dfbc-6600-4ce9-9c32-b6fcf464bd39)

Resolves #119 #120 #121

2023-11-19 14:02 UTC, 0m3ga13 requested changes
remove the search bar from mobile view

2023-11-19 16:26 UTC, medshk approved these changes

2023-11-19 20:42 UTC, 0m3ga13 commented
check this @Bolphunga  
![image](https://github.com/202306-NEA-DZ-FEW/student-store-team-2/assets/62702326/488a3de6-e823-4e08-a44f-4e9e71073902)

2023-11-20 14:07 UTC, 0m3ga13 approved these changes
PR APPROVED

2023-11-20 14:11 UTC, merged