feat(navbar): create a navbar
202306-NEA-DZ-FEW/student-store-team-2 pull request #29
Opened 2023-10-17 00:01 UTC by 0m3ga13

in this changes we created a navbar using headless ui transition and disclosure, and we made sure it functionality in the mobile view

Resolve #19

2023-10-17 13:30 UTC, Bolphunga requested changes

2023-10-17 13:30 UTC, Bolphunga commented on src/components/navbar/Navbar.jsx
> +        { name: "Dashboard", href: "/" },
Change the "Dashnoard" to 'Home."

2023-10-17 13:30 UTC, Bolphunga commented on src/components/portal/Portal.jsx
> +        // useEffect(() => {
This commented section is unnecessary. It needs to be removed.

2023-10-17 13:40 UTC, 0m3ga13 commented on src/components/navbar/Navbar.jsx
> +        { name: "Dashboard", href: "/" },
done

2023-10-17 20:19 UTC, Bolphunga approved these changes
Good job. Approved.

2023-10-18 15:22 UTC, samiraTbl approved these changes
done!

2023-10-18 15:23 UTC, merged

2023-10-18 15:23 UTC, medshk approved these changes
PR permitted