feat(addedgrid.jsx): creating a component about grid
202306-NEA-DZ-FEW/student-store-team-2 pull request #61
Opened 2023-10-29 17:26 UTC by samiraTbl

description: i designed a banner feature.
screenshot md:
![image](https://github.com/202306-NEA-DZ-FEW/student-store-team-2/assets/138632281/46eb3cf8-96cd-4201-963d-6969b9ebc67d)
screenshot sm:
![image](https://github.com/202306-NEA-DZ-FEW/student-store-team-2/assets/138632281/4b00300b-881e-4b42-a4e8-d4082f945e67)

issue: Features Banner #56

2023-10-29 20:41 UTC, 0m3ga13 requested changes

2023-10-29 20:41 UTC, 0m3ga13 commented on messages/en.json
> +        "recently added":"recently added"
missing , in this line

2023-10-29 20:48 UTC, samiraTbl commented on messages/en.json
> +        "recently added":"recently added"
I ll fix it

2023-10-30 11:37 UTC, medshk approved these changes
PR permitted well done

2023-10-30 20:27 UTC, 0m3ga13 approved these changes

2023-10-31 14:01 UTC, merged